CREATE TABLE IF NOT EXISTS PATIENTS(ID VARCHAR PRIMARY KEY NOT NULL,
    FIRSTNAME VARCHAR NOT NULL,
    SURNAME VARCHAR NOT NULL,
    GENDER VARCHAR NOT NULL,
    PHONE VARCHAR NOT NULL,
    NAT VARCHAR NOT NULL,
    EMAIL VARCHAR NOT NULL,
    NOTES VARCHAR);